
name: Update Documentation

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Build documentation
        run: |
          python -m pip install pipenv
          pipenv install --dev --python 3.13
          pipenv run docs

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: html-docs
          path: docs/_build/html/
